### ISSUE TITLE
Problems when load Drosophila Dataset.

### ISSUE THREAD

**Issue by mangoyuan** [JorisRoels/domain-adaptive-segmentation#1]
When i run the `python train_unsupervised.py --method ynet --target drosophila`.  Error `FileNotFoundError: [Errno 2] No such file or directory: '/path/to/drosophila/stack1/data.tif'` occured. I find that in [groundtruth-drosophila-vnc](https://github.com/unidesigner/groundtruth-drosophila-vnc), the training set is like `groundtruth-drosophila-vnc/stack1/raw/00.tif`. Is there any suggestions to solve this.
   And can this repository reproduce the results mentioned in paper?
   thanks.

**Comment by JorisRoels** [comment]
Thanks for submitting this issue. The drosophila data was slightly pre-processed before developing this code. I will include this part in the code as soon as possible. 

Yes, this repository can reproduce the paper results.
