### ISSUE TITLE
Question about the running result

### ISSUE THREAD

**Issue by GWwangshuo** [JorisRoels/domain-adaptive-segmentation#2]
Thanks for your interesting work. I am running your code and getting below result which seems strange. Why the Jaccard src and Total loss are both negative? Could you tell me are these correct or not? Thanks.

![image](https://user-images.githubusercontent.com/6948631/57784136-fbb53280-7761-11e9-950f-17229306effe.png)

**Comment by JorisRoels** [comment]
For segmentation, we typically want to maximize the Jaccard index `J`, which is equivalent to minimizing `-J`. The MSE should be minimized and is always positive, so the total loss (the sum of negative and positive term) can be negative.

**Comment by GWwangshuo** [comment]
@JorisRoels  Thanks for your quickly response, I am really appreciate it. By the way, I am noticed that `FIB-SEM HeLa dataset` is used in your experiment. However, I cannot find this dataset online. Could you please give some suggestion to let me get access to this dataset? Thanks a lot.

**Comment by JorisRoels** [comment]
Sorry, but this dataset is private.
